defaults: &defaults
  appid: 160520280625515
  secret: 370122eb013a4833ea0798a34540a0a3
  authorize_url: https://graph.facebook.com/oauth/authorize
  access_token_url: https://graph.facebook.com/oauth/access_token
  profile_url: https://graph.facebook.com/me

development:
  <<: *defaults

staging:
  <<: *defaults
  appid: 182370788441621
  secret: bbb066ca7a441afa4dc8a4bd82f16d4d

production:
  <<: *defaults
