keys:
  account_settings.delete
  actions.unfollow
  actions.follow
  actions.block
  actions.unblock
  actions.view_more
  actions.show
  actions.hide
  radio.create_new_station
  blocks.blocked
  datetime.distance_in_words.less_than_x_minutes
  datetime.distance_in_words.x_days
  datetime.distance_in_words.x_hours
  datetime.distance_in_words.x_minutes
  datetime.distance_in_words.x_seconds
  actions.pending
  share.errors.message.invalid_url
  coke_messenger.layers.share_mix_layer.name_blank
  coke_messenger.layers.share_mix_layer.email_blank
  coke_messenger.layers.share_mix_layer.invalid_email
  coke_messenger.layers.share_mix_layer.time_out_error
  coke_messenger.layers.share_mix_layer.invalid_msg
  basics.name
  basics.email
  basics.message