Coke Brazil:
  name: Coke Brazil
  deploy_name: coke_brazil
  code: cokebr
  domains:
    - staging.coke.br.hoodiny.com

Coke Latam:
  name: Coke Latam
  deploy_name: coke_latam
  code: cokelatam
  domains:
    - staging.coke.latam.hoodiny.com