Coke Brazil:
  name: Coke Brazil
  deploy_name: coke_brazil
  code: cokebr
  domains:
    - staging.br.coke.hoodiny.com

Coke Latam:
  name: Coke Latam
  deploy_name: coke_latam
  code: cokelatam
  domains:
    - staging.latam.coke.hoodiny.com
    