Coke Brazil:
  name: Coke Brazil
  deploy_name: coke_brazil
  code: cokebr
  domains:
    - staging.br.coke.hoodiny.com
    - br-ko.cyloop.com
    - br.cocacola.fm

Coke Latam:
  name: Coke Latam
  deploy_name: coke_latam
  code: cokelatam
  domains:
    - staging.latam.coke.hoodiny.com
    - latam-ko.cyloop.com
    - latam.cocacola.fm    
