defaults: &defaults
  client_id: 000000004004753A
  secret: pbZ1V8qGMrjKW3DHJZO7viehlvlIUfLZ

development:
  <<: *defaults

staging:
  <<: *defaults
  client_id: 0000000048046D5E
  secret: CZ3siPiOlJlkblO5ilEe2fdH1EvFtZlp

production:
  <<: *defaults

